import { TriviaQuestion } from '@/utils/types';

export const triviaQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: 'What is the capital of France?',
    correctAnswer: 'Paris',
    wrongAnswers: ['Berlin', 'Madrid', 'Rome'],
  },
  {
    id: 2,
    question: "Who wrote the play 'Romeo and Juliet'?",
    correctAnswer: 'William Shakespeare',
    wrongAnswers: ['Charles Dickens', 'George Orwell', 'Mark Twain'],
  },
  {
    id: 3,
    question: 'What is the smallest planet in our solar system?',
    correctAnswer: 'Mercury',
    wrongAnswers: ['Venus', 'Mars', 'Pluto'],
  },
  {
    id: 4,
    question: 'How many continents are there on Earth?',
    correctAnswer: 'Seven',
    wrongAnswers: ['Six', 'Eight', 'Five'],
  },
  {
    id: 5,
    question: 'What is the chemical symbol for gold?',
    correctAnswer: 'Au',
    wrongAnswers: ['Ag', 'Fe', 'Pb'],
  },
  {
    id: 6,
    question: 'Who was the first President of the United States?',
    correctAnswer: 'George Washington',
    wrongAnswers: ['Thomas Jefferson', 'Abraham Lincoln', 'John Adams'],
  },
  {
    id: 7,
    question: 'In which year did the Titanic sink?',
    correctAnswer: '1912',
    wrongAnswers: ['1905', '1915', '1920'],
  },
  {
    id: 7,
    question: 'Who discovered penicillin?',
    correctAnswer: 'Alexander Fleming',
    wrongAnswers: ['Marie Curie', 'Isaac Newton', 'Louis Pasteur'],
  },
  {
    id: 8,
    question: 'What ancient civilization built the pyramids?',
    correctAnswer: 'The Egyptians',
    wrongAnswers: ['The Greeks', 'The Romans', 'The Mayans'],
  },
  {
    id: 9,
    question:
      'Which war was fought between the North and South regions in the United States?',
    correctAnswer: 'The Civil War',
    wrongAnswers: ['The Revolutionary War', 'World War I', 'The War of 1812'],
  },
  {
    id: 10,
    question: 'What is the powerhouse of the cell?',
    correctAnswer: 'Mitochondria',
    wrongAnswers: ['Nucleus', 'Ribosome', 'Chloroplast'],
  },
  {
    id: 11,
    question: 'What planet is known as the Red Planet?',
    correctAnswer: 'Mars',
    wrongAnswers: ['Venus', 'Jupiter', 'Saturn'],
  },
  {
    id: 12,
    question: 'What is the hardest natural substance on Earth?',
    correctAnswer: 'Diamond',
    wrongAnswers: ['Gold', 'Iron', 'Platinum'],
  },
  {
    id: 13,
    question: 'What gas do plants absorb from the atmosphere?',
    correctAnswer: 'Carbon Dioxide',
    wrongAnswers: ['Oxygen', 'Nitrogen', 'Hydrogen'],
  },
  {
    id: 14,
    question: 'How many bones are in the human body?',
    correctAnswer: '206',
    wrongAnswers: ['205', '210', '212'],
  },
  {
    id: 15,
    question: 'What is the longest river in the world?',
    correctAnswer: 'Nile River',
    wrongAnswers: ['Amazon River', 'Yangtze River', 'Mississippi River'],
  },
  {
    id: 16,
    question: 'Which country has the most population?',
    correctAnswer: 'China',
    wrongAnswers: ['India', 'United States', 'Indonesia'],
  },
  {
    id: 17,
    question: 'What is the largest desert in the world?',
    correctAnswer: 'Sahara Desert',
    wrongAnswers: ['Gobi Desert', 'Kalahari Desert', 'Arabian Desert'],
  },
  {
    id: 18,
    question: 'Which country is known as the Land of the Rising Sun?',
    correctAnswer: 'Japan',
    wrongAnswers: ['China', 'South Korea', 'Thailand'],
  },
  {
    id: 19,
    question: 'What is the tallest mountain in the world?',
    correctAnswer: 'Mount Everest',
    wrongAnswers: ['K2', 'Kangchenjunga', 'Lhotse'],
  },
  {
    id: 20,
    question: "Who directed the movie 'Jurassic Park'?",
    correctAnswer: 'Steven Spielberg',
    wrongAnswers: ['James Cameron', 'George Lucas', 'Martin Scorsese'],
  },
  {
    id: 21,
    question: "Which singer is known as the 'Queen of Pop'?",
    correctAnswer: 'Madonna',
    wrongAnswers: ['Britney Spears', 'Lady Gaga', 'Beyoncé'],
  },
  {
    id: 22,
    question: 'In which year were the first Academy Awards (Oscars) held?',
    correctAnswer: '1929',
    wrongAnswers: ['1930', '1925', '1932'],
  },
  {
    id: 23,
    question: "Who played Jack Dawson in the movie 'Titanic'?",
    correctAnswer: 'Leonardo DiCaprio',
    wrongAnswers: ['Brad Pitt', 'Johnny Depp', 'Tom Cruise'],
  },
  {
    id: 24,
    question:
      "What is the name of the fictional wizarding school in the 'Harry Potter' series?",
    correctAnswer: 'Hogwarts',
    wrongAnswers: ['Beauxbatons', 'Durmstrang', 'Ilvermorny'],
  },
  {
    id: 25,
    question: 'How many players are there in a soccer team?',
    correctAnswer: 'Eleven',
    wrongAnswers: ['Ten', 'Twelve', 'Nine'],
  },
  {
    id: 26,
    question: 'In which sport can you win the Davis Cup?',
    correctAnswer: 'Tennis',
    wrongAnswers: ['Golf', 'Cricket', 'Rugby'],
  },
  {
    id: 27,
    question:
      'Who holds the record for the most home runs in a single MLB season?',
    correctAnswer: 'Barry Bonds',
    wrongAnswers: ['Babe Ruth', 'Hank Aaron', 'Mark McGwire'],
  },
  {
    id: 28,
    question: 'Which country won the FIFA World Cup in 2018?',
    correctAnswer: 'France',
    wrongAnswers: ['Germany', 'Brazil', 'Argentina'],
  },
  {
    id: 29,
    question: "Who is known as 'The Great One' in hockey?",
    correctAnswer: 'Wayne Gretzky',
    wrongAnswers: ['Mario Lemieux', 'Gordie Howe', 'Bobby Orr'],
  },
  {
    id: 30,
    question: "Who wrote 'To Kill a Mockingbird'?",
    correctAnswer: 'Harper Lee',
    wrongAnswers: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck'],
  },
  {
    id: 31,
    question:
      "What is the name of the hobbit played by Elijah Wood in the 'Lord of the Rings' movies?",
    correctAnswer: 'Frodo Baggins',
    wrongAnswers: ['Samwise Gamgee', 'Bilbo Baggins', 'Meriadoc Brandybuck'],
  },
  {
    id: 32,
    question: "Who is the author of 'The Catcher in the Rye'?",
    correctAnswer: 'J.D. Salinger',
    wrongAnswers: ['William Faulkner', 'John Steinbeck', 'Kurt Vonnegut'],
  },
  {
    id: 33,
    question: 'What is the title of the first Harry Potter book?',
    correctAnswer: "Harry Potter and the Philosopher's Stone",
    wrongAnswers: [
      'Harry Potter and the Chamber of Secrets',
      'Harry Potter and the Prisoner of Azkaban',
      'Harry Potter and the Goblet of Fire',
    ],
  },
  {
    id: 34,
    question: "Who wrote 'Pride and Prejudice'?",
    correctAnswer: 'Jane Austen',
    wrongAnswers: ['Charlotte Brontë', 'Mary Shelley', 'Emily Brontë'],
  },
  {
    id: 35,
    question: 'Who is the lead singer of the band Queen?',
    correctAnswer: 'Freddie Mercury',
    wrongAnswers: ['Mick Jagger', 'Robert Plant', 'David Bowie'],
  },
  {
    id: 36,
    question: "Which band released the album 'The Dark Side of the Moon'?",
    correctAnswer: 'Pink Floyd',
    wrongAnswers: ['Led Zeppelin', 'The Rolling Stones', 'The Beatles'],
  },
  {
    id: 37,
    question: 'What is the highest-selling album of all time?',
    correctAnswer: "'Thriller' by Michael Jackson",
    wrongAnswers: [
      "'Back in Black' by AC/DC",
      "'The Dark Side of the Moon' by Pink Floyd",
      "'The Wall' by Pink Floyd",
    ],
  },
  {
    id: 38,
    question: "Who is known as the 'King of Pop'?",
    correctAnswer: 'Michael Jackson',
    wrongAnswers: ['Elvis Presley', 'Prince', 'Freddie Mercury'],
  },
  {
    id: 39,
    question: "Which composer created the 'Four Seasons'?",
    correctAnswer: 'Antonio Vivaldi',
    wrongAnswers: [
      'Johann Sebastian Bach',
      'Ludwig van Beethoven',
      'Wolfgang Amadeus Mozart',
    ],
  },
  {
    id: 40,
    question: 'What is the main ingredient in guacamole?',
    correctAnswer: 'Avocado',
    wrongAnswers: ['Tomato', 'Cucumber', 'Bell Pepper'],
  },
  {
    id: 41,
    question: 'Which country is famous for its sushi?',
    correctAnswer: 'Japan',
    wrongAnswers: ['China', 'South Korea', 'Thailand'],
  },
  {
    id: 42,
    question:
      'What is the most widely consumed alcoholic beverage in the world?',
    correctAnswer: 'Beer',
    wrongAnswers: ['Wine', 'Whiskey', 'Vodka'],
  },
  {
    id: 43,
    question: 'What type of pastry is used to make a croissant?',
    correctAnswer: 'Puff pastry',
    wrongAnswers: ['Shortcrust pastry', 'Filo pastry', 'Choux pastry'],
  },
  {
    id: 44,
    question: "Which fruit is known as the 'king of fruits'?",
    correctAnswer: 'Mango',
    wrongAnswers: ['Apple', 'Pineapple', 'Banana'],
  },
  {
    id: 45,
    question: 'Who founded Microsoft?',
    correctAnswer: 'Bill Gates and Paul Allen',
    wrongAnswers: [
      'Steve Jobs and Steve Wozniak',
      'Larry Page and Sergey Brin',
      'Mark Zuckerberg and Eduardo Saverin',
    ],
  },
  {
    id: 46,
    question: 'What does HTTP stand for?',
    correctAnswer: 'HyperText Transfer Protocol',
    wrongAnswers: [
      'HyperText Transfer Platform',
      'Hyper Transfer Text Protocol',
      'HyperText Transmission Protocol',
    ],
  },
  {
    id: 47,
    question: 'What was the first smartphone ever released?',
    correctAnswer: 'IBM Simon',
    wrongAnswers: ['iPhone', 'Nokia 3310', 'Motorola DynaTAC'],
  },
  {
    id: 48,
    question: 'Which company is known for the iPhone?',
    correctAnswer: 'Apple',
    wrongAnswers: ['Samsung', 'Google', 'Microsoft'],
  },
  {
    id: 49,
    question: 'What is the name of the first programmable computer?',
    correctAnswer: 'ENIAC',
    wrongAnswers: ['UNIVAC', 'IBM PC', 'Altair 8800'],
  },
  {
    id: 50,
    question: "Who played Forrest Gump in the movie 'Forrest Gump'?",
    correctAnswer: 'Tom Hanks',
    wrongAnswers: ['Brad Pitt', 'Harrison Ford', 'Kevin Costner'],
  },
  {
    id: 51,
    question: 'What is the highest-grossing film of all time?',
    correctAnswer: 'Avengers: Endgame',
    wrongAnswers: ['Avatar', 'Titanic', 'Star Wars: The Force Awakens'],
  },
  {
    id: 52,
    question: "Who directed 'Inception'?",
    correctAnswer: 'Christopher Nolan',
    wrongAnswers: ['Steven Spielberg', 'Quentin Tarantino', 'James Cameron'],
  },
  {
    id: 53,
    question: "Which movie features the song 'My Heart Will Go On'?",
    correctAnswer: 'Titanic',
    wrongAnswers: ['The Bodyguard', 'Pretty Woman', 'Ghost'],
  },
  {
    id: 54,
    question: "What year was the first 'Star Wars' movie released?",
    correctAnswer: '1977',
    wrongAnswers: ['1980', '1983', '1974'],
  },
  {
    id: 55,
    question: 'What is the longest-running TV show in the United States?',
    correctAnswer: 'The Simpsons',
    wrongAnswers: ['Gunsmoke', 'Law & Order', "Grey's Anatomy"],
  },
  {
    id: 56,
    question: "Who played Rachel Green on 'Friends'?",
    correctAnswer: 'Jennifer Aniston',
    wrongAnswers: ['Courteney Cox', 'Lisa Kudrow', 'Julia Roberts'],
  },
  {
    id: 57,
    question: 'Which TV series features the character Sheldon Cooper?',
    correctAnswer: 'The Big Bang Theory',
    wrongAnswers: ['Friends', 'How I Met Your Mother', 'Scrubs'],
  },
  {
    id: 58,
    question: "What is the name of the coffee shop in 'Friends'?",
    correctAnswer: 'Central Perk',
    wrongAnswers: ["Monk's Café", "Java Joe's", 'The Hub'],
  },
  {
    id: 59,
    question: "Who was the original host of 'The Tonight Show'?",
    correctAnswer: 'Steve Allen',
    wrongAnswers: ['Johnny Carson', 'Jack Paar', 'Jay Leno'],
  },
  {
    id: 60,
    question: 'What is the largest mammal in the world?',
    correctAnswer: 'Blue Whale',
    wrongAnswers: ['Elephant', 'Giraffe', 'Hippopotamus'],
  },
  {
    id: 61,
    question: 'How many legs does a spider have?',
    correctAnswer: 'Eight',
    wrongAnswers: ['Six', 'Ten', 'Twelve'],
  },
  {
    id: 62,
    question: 'What is a group of lions called?',
    correctAnswer: 'A pride',
    wrongAnswers: ['A pack', 'A herd', 'A colony'],
  },
  {
    id: 63,
    question: 'Which bird is known for its colorful tail feathers?',
    correctAnswer: 'Peacock',
    wrongAnswers: ['Parrot', 'Flamingo', 'Canary'],
  },
  {
    id: 64,
    question: 'What is the fastest land animal?',
    correctAnswer: 'Cheetah',
    wrongAnswers: ['Lion', 'Leopard', 'Horse'],
  },
  {
    id: 65,
    question: 'Who painted the Mona Lisa?',
    correctAnswer: 'Leonardo da Vinci',
    wrongAnswers: ['Vincent van Gogh', 'Pablo Picasso', 'Claude Monet'],
  },
  {
    id: 66,
    question:
      'What is the art style characterized by small, thin brush strokes called?',
    correctAnswer: 'Impressionism',
    wrongAnswers: ['Cubism', 'Surrealism', 'Realism'],
  },
  {
    id: 67,
    question: "Who painted 'The Starry Night'?",
    correctAnswer: 'Vincent van Gogh',
    wrongAnswers: ['Claude Monet', 'Paul Cézanne', 'Henri Matisse'],
  },
  {
    id: 68,
    question:
      'What is the name of the museum where the Mona Lisa is displayed?',
    correctAnswer: 'The Louvre',
    wrongAnswers: [
      'The British Museum',
      'The Metropolitan Museum of Art',
      'The Prado',
    ],
  },
  {
    id: 69,
    question: "Who sculpted 'David'?",
    correctAnswer: 'Michelangelo',
    wrongAnswers: ['Donatello', 'Leonardo da Vinci', 'Raphael'],
  },
  {
    id: 70,
    question: 'What is the most spoken language in the world?',
    correctAnswer: 'Mandarin Chinese',
    wrongAnswers: ['English', 'Spanish', 'Hindi'],
  },
  {
    id: 71,
    question: 'What language has the most words?',
    correctAnswer: 'English',
    wrongAnswers: ['Chinese', 'Spanish', 'French'],
  },
  {
    id: 72,
    question: 'How many letters are in the Greek alphabet?',
    correctAnswer: '24',
    wrongAnswers: ['26', '22', '28'],
  },
  {
    id: 73,
    question: 'What is the official language of Brazil?',
    correctAnswer: 'Portuguese',
    wrongAnswers: ['Spanish', 'French', 'English'],
  },
  {
    id: 74,
    question: 'Which language is primarily spoken in Austria?',
    correctAnswer: 'German',
    wrongAnswers: ['French', 'Italian', 'Dutch'],
  },
  {
    id: 75,
    question: 'How many moons does Mars have?',
    correctAnswer: 'Two',
    wrongAnswers: ['One', 'Three', 'Four'],
  },
  {
    id: 76,
    question: 'What is the closest star to Earth?',
    correctAnswer: 'The Sun',
    wrongAnswers: ['Proxima Centauri', 'Alpha Centauri', "Barnard's Star"],
  },
  {
    id: 77,
    question: 'What galaxy is Earth located in?',
    correctAnswer: 'The Milky Way',
    wrongAnswers: ['Andromeda Galaxy', 'Triangulum Galaxy', 'Whirlpool Galaxy'],
  },
  {
    id: 78,
    question: 'Who was the first person to walk on the moon?',
    correctAnswer: 'Neil Armstrong',
    wrongAnswers: ['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'],
  },
  {
    id: 79,
    question: 'What planet is known as the Gas Giant?',
    correctAnswer: 'Jupiter',
    wrongAnswers: ['Saturn', 'Neptune', 'Uranus'],
  },
  {
    id: 80,
    question: 'Who is the king of the Greek gods?',
    correctAnswer: 'Zeus',
    wrongAnswers: ['Poseidon', 'Hades', 'Apollo'],
  },
  {
    id: 81,
    question: "What is the name of Thor's hammer?",
    correctAnswer: 'Mjölnir',
    wrongAnswers: ['Stormbreaker', 'Gungnir', 'Skofnung'],
  },
  {
    id: 82,
    question: 'In Egyptian mythology, who is the god of the underworld?',
    correctAnswer: 'Osiris',
    wrongAnswers: ['Ra', 'Anubis', 'Horus'],
  },
  {
    id: 83,
    question: 'Who was the Roman god of war?',
    correctAnswer: 'Mars',
    wrongAnswers: ['Jupiter', 'Neptune', 'Apollo'],
  },
  {
    id: 84,
    question: 'In Norse mythology, what is the name of the world tree?',
    correctAnswer: 'Yggdrasil',
    wrongAnswers: ['Bifröst', 'Ragnarök', 'Asgard'],
  },
  {
    id: 85,
    question: 'Who is the CEO of Amazon as of 2023?',
    correctAnswer: 'Andy Jassy',
    wrongAnswers: ['Jeff Bezos', 'Tim Cook', 'Satya Nadella'],
  },
  {
    id: 86,
    question: 'Which company is known for its swoosh logo?',
    correctAnswer: 'Nike',
    wrongAnswers: ['Adidas', 'Puma', 'Reebok'],
  },
  {
    id: 87,
    question: 'What is the currency of Japan?',
    correctAnswer: 'Yen',
    wrongAnswers: ['Won', 'Dollar', 'Euro'],
  },
  {
    id: 88,
    question: 'Who founded Tesla Motors?',
    correctAnswer:
      'Elon Musk, JB Straubel, Martin Eberhard, Marc Tarpenning, and Ian Wright',
    wrongAnswers: [
      'Steve Jobs, Steve Wozniak, and Ronald Wayne',
      'Bill Gates and Paul Allen',
      'Larry Page and Sergey Brin',
    ],
  },
  {
    id: 89,
    question: 'What is the largest e-commerce company in China?',
    correctAnswer: 'Alibaba',
    wrongAnswers: ['JD.com', 'Tencent', 'Baidu'],
  },
  {
    id: 90,
    question: 'What is the tallest tree species in the world?',
    correctAnswer: 'Coast Redwood',
    wrongAnswers: ['Giant Sequoia', 'Douglas Fir', 'Sitka Spruce'],
  },
  {
    id: 91,
    question: 'What is the fastest bird in the world?',
    correctAnswer: 'Peregrine Falcon',
    wrongAnswers: ['Golden Eagle', 'Bald Eagle', 'Harpy Eagle'],
  },
  {
    id: 92,
    question: 'What is the largest species of shark?',
    correctAnswer: 'Whale Shark',
    wrongAnswers: ['Great White Shark', 'Hammerhead Shark', 'Tiger Shark'],
  },
];
